#!/usr/bin/env php

<?php

use Tamdaz\Doc2Html\Exceptions\EmptyNamespacesException;
use Tamdaz\Doc2Html\LoggerOutput;
use Phalcon\Cop\Parser;
use Tamdaz\Doc2Html\Reflectors;

require_once "vendor/autoload.php";

$parser = new Parser();
$args = $parser->parse();

if ($parser->has("gen-config")) {
    copy(
        __DIR__ . '/generators/doc2html.config.php',
        __DIR__ . '/doc2html.config.php'
    );

    LoggerOutput::success("Successfully generated \"doc2html.config.php\" file.\n");

    exit(0);
}

$reflector = new Reflectors();

try {
    $reflector->run();
} catch (EmptyNamespacesException|DOMException|Exception $e) {
    LoggerOutput::error("[{$e->getCode()}]: {$e->getMessage()}\n");
}