#!/usr/bin/env php

<?php

use Tamdaz\Doc2web\ClassReflector;

require_once "vendor/autoload.php";

$selectedNamespace = "Examples";

$reflector = new ClassReflector($selectedNamespace);
$reflector->run();