#!/usr/bin/env php

<?php

use Tamdaz\Doc2Html\{ClassReflector, Config, ObjectRegister};

require_once "vendor/autoload.php";

$objectRegister = ObjectRegister::getInstance();

$namespaces = Config::getTargetNamespaces();

foreach ($namespaces as $namespace)
    $objectRegister->registerNamespace($namespace);

$reflector = new ClassReflector();

$reflector->run();