#!/usr/bin/env php

<?php

use Tamdaz\Doc2web\ClassReflector;

require_once "vendor/autoload.php";

try {
    $reflector = new ClassReflector("Examples");
    $reflector->run();
} catch (Exception $e) {
    echo $e->getMessage();
}